Implementation
Mih-Mir/RequestTimeTrackingMiddleware pull request #1
Opened 2021-06-10 07:34 UTC by Mih-Mir

2021-06-11 15:56 UTC, AndreyYurashevich requested changes

2021-06-11 15:56 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware.ResourceAccess/Repositories/ProfileRepository.cs
> +            await using (_appDbContext)
You don't actually need to wrap _appDbContext in using statements because DI container is responsible for that. See [the article ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#disposal-of-services) for details.

2021-06-11 15:56 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware.ResourceAccess/Repositories/ProfileRepository.cs
> +                _appDbContext.Update(user);
You don't need to explicitly call Update here. See [the Change Tracking](https://docs.microsoft.com/en-us/ef/core/change-tracking/) article for details.

2021-06-11 15:56 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware/Controllers/ProfilesController.cs
> +            return Ok(ModelState);
It's better to indicate errors properly using the appropriate error code (400 in this case). See [the article](https://docs.microsoft.com/en-us/dotnet/api/system.web.http.apicontroller.badrequest?view=aspnetcore-2.2) for details.

2021-06-11 15:56 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware/Controllers/ProfilesController.cs
> +            if (ModelState.IsValid)
There couldn't be an invalid model state, could it?

2021-06-11 15:56 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware.Data/SeedData/SeedData.cs
> +            await using var context = new AppDbContext(serviceProvider.GetRequiredService<DbContextOptions<AppDbContext>>());
1. You should not try disposing the context as it was created in a scope.
2. You could request AppDbContext object directly.

2021-06-11 15:56 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware/Program.cs
> +                    throw new NotImplementedException();
Please avoid such meaningless catch blocks as they obscure actual errors and unnecessary complicate troubleshooting.

2021-06-15 06:41 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware.ResourceAccess/Repositories/ProfileRepository.cs
> +            await using (_appDbContext)
Fixed

2021-06-15 06:49 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware.ResourceAccess/Repositories/ProfileRepository.cs
> +                _appDbContext.Update(user);
Fixed.

2021-06-15 06:55 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware/Controllers/ProfilesController.cs
> +            return Ok(ModelState);
Done.

2021-06-15 06:55 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware/Controllers/ProfilesController.cs
> +            if (ModelState.IsValid)
Yes, fixed.

2021-06-15 06:58 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware.Data/SeedData/SeedData.cs
> +            await using var context = new AppDbContext(serviceProvider.GetRequiredService<DbContextOptions<AppDbContext>>());
Done.

2021-06-15 07:01 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware/Program.cs
> +                    throw new NotImplementedException();
Understood. Done.

2021-06-16 09:54 UTC, AndreyYurashevich requested changes

2021-06-16 09:54 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware.ResourceAccess/Repositories/ProfileRepository.cs
> +            _appDbContext.ChangeTracker.DetectChanges();
Actually calling DetectChanges is also not required as SaveChangesAsync calls it automatically

2021-06-16 09:54 UTC, AndreyYurashevich commented on RequestTimeTrackingMiddleware.Data/SeedData/SeedData.cs
> +            var context = new AppDbContext(serviceProvider.GetRequiredService<DbContextOptions<AppDbContext>>());
You could ask AppDbContext directly: `serviceProvider.GetRequiredService<AppDbContext>()`

2021-06-16 19:33 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware.ResourceAccess/Repositories/ProfileRepository.cs
> +            _appDbContext.ChangeTracker.DetectChanges();
Understood. Fixed

2021-06-16 19:37 UTC, Mih-Mir commented on RequestTimeTrackingMiddleware.Data/SeedData/SeedData.cs
> +            var context = new AppDbContext(serviceProvider.GetRequiredService<DbContextOptions<AppDbContext>>());
Sure. Fixed.

2021-06-17 07:47 UTC, AndreyYurashevich approved these changes
Looks great to me!

2021-06-17 07:53 UTC, merged